name: Mood_bot Daily Run

on:
  schedule:
    - cron: "0 13 * * *"  # 09:00 ET
    - cron: "0 0 * * *"  # 20:00 ET
  workflow_dispatch:  

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      PEXELS_API: ${{ secrets.PEXELS_API }}
      ELEVEN_API: ${{ secrets.ELEVEN_API }}
      YT_API: ${{ secrets.YT_API }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      HAS_CRED: ${{ secrets.YT_CREDENTIALS != '' }}
      HAS_TOKEN: ${{ secrets.TOKEN_JSON != '' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt


        # ✅ ไฟล์ว่าง
      - name: Create empty state files if missing
        run: |
          [ -f token.json ] || echo "{}" > token.json

      - name: Create credentials.json
        if: ${{ env.HAS_CRED }}
        run: printf '%s' '${{ secrets.YT_CREDENTIALS }}' > credentials.json

        # ✅ token.json (สร้างถ้ามี secret)
      - name: Create token.json
        if: ${{ env.HAS_TOKEN }}
        run: printf '%s' '${{ secrets.TOKEN_JSON }}' > token.json

      # ✅ Validate JSON
      - name: Validate JSON files
        run: |
          python -m json.tool credentials.json > /dev/null
          python -m json.tool token.json > /dev/null

      - name: Run Daily Bot
        run: python main.py


      # ✅ Save state
      - name: Save initial state files
        uses: actions/upload-artifact@v4
        with:
          name: state-files
          path: |
            token.json
            credentials.json
